### ISSUE TITLE
[Feature request] Command for fast play with streamlink

### ISSUE THREAD

**Issue by neilschark** [andresterba/streamstatus#5]
A nice feature would be, if you could start streamlink with a command of your tool.

For example `streamstatus play 1` plays stream 1, `streamstatus play random` plays a random stream from your list which is online, `streamstatus play random 4` plays 4 random streams from the list which are online and so on.

Nice work btw, keep going.

**Comment by andresterba** [comment]
This is out of scope of this project.
I do not want to depend on external programs on the user machine.
